### ISSUE TITLE
Inter-read distance/squished reads

### ISSUE THREAD

**Issue by asifrim** [wtsi-medical-genomics/snoopy#8]
There currently is too much whitespace between reads, IGV allows having 1 px reads which are stacked upon eachother without dividing space ("squished" reads). This would optimize vertical space, specially when looking at multiple bams.

**Comment by dlrice** [comment]
Fixed with 0.4.0
![screen shot 2016-06-14 at 14 39 29](https://cloud.githubusercontent.com/assets/4357962/16044842/ecbee490-323d-11e6-93cb-d28228cdaea2.png)
